### ISSUE TITLE
unimplemented RSA signature hash type: HashSHA384

### ISSUE THREAD

**Issue by jprider63** [denibertovic/docker-hs#10]
I was getting the following error while attempting to connect with ssl:

    TlsExceptionHostPort (HandshakeFailed (Error_Misc "unimplemented RSA signature hash type: HashSHA384"))

It looks like support for HashSHA384 was added in tls-1.3.7. I'm currently updating to stackage lts-5.18, so hopefully that takes care of it. 

This issue is mostly for future reference in case someone else runs into this problem.

**Comment by denibertovic** [comment]
Thanks. I'd like to leave the issue open as a reminder.

**Comment by denibertovic** [comment]
Closing this as it was resolved.
