### ISSUE TITLE
Travis build fails because precise vs. trusty issue

### ISSUE THREAD

**Issue by denibertovic** [denibertovic/docker-hs#14]
Since we're targeting docker 1.12 and Travis has not yet upgraded to that version we're installing it manually (see travis.yml). The issue is that the package name (and apt repo for that matter) has to reference the correct Ubuntu version but Travis is apparently switching between Precise and Trusty randomly on each job.

**Comment by denibertovic** [comment]
This should fix the problem: https://github.com/denibertovic/docker-hs/commit/d55e575d49f037cd5efa2ce432b77b141a580abe by specifically requiring trusty.

However the test are failing: https://travis-ci.org/denibertovic/docker-hs/builds/151017201 for some reason.

**Comment by denibertovic** [comment]
It seems it was a cache issue. I'm not entirely sure how that happened but clearing the cache helped.
https://travis-ci.org/denibertovic/docker-hs/builds/151017201

Closing.

**Comment by denibertovic** [comment]
Apparently this is not fixed: https://travis-ci.org/denibertovic/docker-hs/builds/151175552

I can't reproduce locally (test pass every time). I'll try and look into it later.

**Comment by jprider63** [comment]
It looks like Travis is working now. Should we close this?

**Comment by denibertovic** [comment]
@jprider63 yeah we can close this...I haven't seen this issue in a while now. If it occurs again we can investigate and we at least we know that clearing the build cache gets it working again.
