### ISSUE TITLE
Deleting "dev" branch

### ISSUE THREAD

**Issue by denibertovic** [denibertovic/docker-hs#27]
Hey @jprider63  @kseo  just wanted to let you know I've deleted the dev branch. I don't think we need the "git-flow" dev branch in this repo since it complicates thing and imo is overkill. From here on we're just going to treat master as the main branch for everything that's coming in (All PR's should be based on master and committed back to it.) 

We will continue to use tags for new releases but HEAD of master should always be stable and working. 

Since I've deleted the dev branch 2 of the open PR's have been closed automatically :(. @kseo these were yours. I'm going to cherry pick those into master once I make time (they had some changes requested so I first have to make those changes... Feel free to re-open a PR to master if you beat me to it.)

**Comment by denibertovic** [comment]
Just wanted to let you guys know. Closing this issue.

**Comment by jprider63** [comment]
Sounds good. What do we need for a 0.4.0.0 hackage release? Just merge @kseo's PRs?

**Comment by denibertovic** [comment]
@jprider63 I only just saw this..... I'm going to release @kseo PR's as a follow up. Didn't wanna wait for that. I might get a change this week to work on it more.

**Comment by jprider63** [comment]
Ok, makes sense.
