### ISSUE TITLE
Update dependencies to work with the stack lts-9 resolver

### ISSUE THREAD

**Issue by DaQuirm** [denibertovic/docker-hs#33]
Hi, thank you for this module!
I'd like to ask, would it be difficult to make it work with the latest stack resolver (lts-9)?
Could I do that and make a contribution?

**Comment by jprider63** [comment]
I imagine it wouldn't be too difficult. If you can do that and maintain backwards compatibility, that would be great!

**Comment by denibertovic** [comment]
@DaQuirm  I don't think it would be too difficult. However, I don't think I'm gonna have time to work on this anytime soon. I'd welcome a PR though if you wanna take a shot at it.

**Comment by locallycompact** [comment]
I had a go at this here https://github.com/denibertovic/docker-hs/pull/34

**Comment by DaQuirm** [comment]
Awesome, thanks you @locallycompact! 💜

**Comment by denibertovic** [comment]
Closed via #35 . Thanks @locallycompact  and @jprider63 once again. :cake:
