### ISSUE TITLE
Add to stackage

### ISSUE THREAD

**Issue by jprider63** [denibertovic/docker-hs#36]
We should add this package to [stackage](https://github.com/fpco/stackage/blob/master/MAINTAINERS.md#adding-a-package). @denibertovic, should you and I be co-maintainers?

**Comment by denibertovic** [comment]
@jprider63 that sounds like a plan! :) I'll make sure to get this done over the weekend.

**Comment by denibertovic** [comment]
I made the necessary version bounds changes and checked that the latest release builds with nightly. I'm going to submit a PR tomorrow with the package added to nightly.

**Comment by jprider63** [comment]
Great thanks!

**Comment by denibertovic** [comment]
PR here: https://github.com/fpco/stackage/pull/2931

@jprider63 this only adds the package to nightly btw...so it's going to be in the next LTS. 
I'm not sure if you wanted to add it to the existing LTS releases?

**Comment by jprider63** [comment]
That's probably fine. Looks like they just merged it. Thanks!
