### ISSUE TITLE
No error message for obviously incorrect request

### ISSUE THREAD

**Issue by portnov** [denibertovic/docker-hs#41]
I try to start or stop a container with empty name, it says ok:

    > runDockerT (defaultClientOpts, h) $ stopContainer DefaultTimeout  $ fromJust $ toContainerID $ T.pack ""
    Right ()

I also get `Right ()` when I supply container id that does not exist on my host.

    Client:
     Version:      1.13.1
     API version:  1.26
     Go version:   go1.9.1
     Git commit:   092cba3
     Built:        Sat Oct 14 16:54:40 2017
     OS/Arch:      linux/amd64

    Server:
     Version:      1.13.1
     API version:  1.26 (minimum version 1.12)
     Go version:   go1.9.1
     Git commit:   092cba3
     Built:        Sat Oct 14 16:54:40 2017
     OS/Arch:      linux/amd64
     Experimental: false

**Comment by portnov** [comment]
If I supply correct container name, it actually works and returns `Right ()` as expected.

**Comment by SKoschnicke** [comment]
Yes, this seems wrong. The docker API returns 404 for a not existing id:

```
> http POST "localhost:2375/v1.24/containers/e90e34656806/stop?t=5"
HTTP/1.1 404 Not Found
Api-Version: 1.32
Content-Length: 46
Content-Type: application/json
Date: Sun, 29 Oct 2017 18:01:24 GMT
Docker-Experimental: false
Ostype: linux
Server: Docker/17.09.0-ce (linux)

{
    "message": "No such container: e90e34656806"
}
```

or a 301 for an empty container id:

```
> http POST "localhost:2375/v1.24/containers//stop?t=5"
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Date: Sun, 29 Oct 2017 18:01:32 GMT
Location: /v1.24/containers/stop?t=5
```
