### ISSUE TITLE
Rename Status to State

### ISSUE THREAD

**Issue by denibertovic** [denibertovic/docker-hs#51]
@jprider63  Since we're actually parsing `State` from the API and not `Status` (which carries more information) should we rename our data type accordingly?

**Comment by jprider63** [comment]
Makes sense to me. 

Docker returns `Status` too, although the documentation isn't very clear what this can be (The only example is `"Exit 0"`). Maybe we should consider adding it. For now we could implement it as a `Maybe String` and consider adding parsing for it in the future.

**Comment by denibertovic** [comment]
Sounds good to me. Do you wanna take it or should I? I think I could have a PR tomorrow or so.

**Comment by jprider63** [comment]
I can look at this now. I don't think it should take too long.

**Comment by denibertovic** [comment]
@jprider63 go for it. Thanks,

**Comment by jprider63** [comment]
I figured out why we called it `Status`. The "INSPECT A CONTAINER" endpoint returns the same type inside of `ContainerState`, but calls it `Status`. Maybe we should just leave the name as is? I can still add `"Status"` parsing to `Container`'s JSON instance.

**Comment by jprider63** [comment]
I've implemented this in #52. One thing we could do is try to come up with an unambiguous name for the `Status` type. I can't really think of any good names though. `ContainerStatus`? `Position`? `Lifecycle`?

**Comment by denibertovic** [comment]
It's basically a description field where it will say things like "created", "Exited (137) 5 days ago" or "Up for 40 hours". 

I think we should just rename the field `status` in `ContainerState` to `state`. And rename the `Status` datatype to `State` that way we hide the docker API missmatch from the user. We only need to be aware of it during parsing (ie. get ContainerState.state from State->Status when inspecting containers and from State when listing Containers.) How does that sound?

**Comment by jprider63** [comment]
Makes sense. I updated the PR.

**Comment by denibertovic** [comment]
Closed via #52
