### ISSUE TITLE
Bump http-conduit

### ISSUE THREAD

**Issue by denibertovic** [denibertovic/docker-hs#54]
@jprider63  Regarding: https://github.com/fpco/stackage/issues/3204

I'm fine with breaking compatibility to be honest. What do you think?

**Comment by denibertovic** [comment]
@jprider63 btw I looked at: https://github.com/jprider63/docker-hs/commit/527cb52fb534b3cb808f23c83c07ab2054479a46

but I'm not sure how it's supposed to work since we have to add `http-conduit-2.3.0` to `stack.yaml`'s `extra-deps` to use that version and not the version in the snapshot.

**Comment by jprider63** [comment]
We can break compatibility if we need to, but I'd prefer not to if we don't have to. Another option is we could always include unliftio-core as a dependency, which I think is not great, but better than breaking compatibility. 

That commit attempts (and fails) to provide successful builds no matter which version of http-conduit is linked against. It should work whether you add `http-conduit-2.3.0` or `http-conduit-2.2.4` to the `stack.yaml`.

**Comment by denibertovic** [comment]
@jprider63 OK agreed. If it's relatively simple to keep backwards compatibility then yes we should try to.

**Comment by denibertovic** [comment]
Thanks @jprider63 Closing this.
