### ISSUE TITLE
building against LTS 15.0

### ISSUE THREAD

**Issue by esjmb** [denibertovic/docker-hs#72]
Hi, 

docker will not presently build as a dependency in projects using LTS-15.0, but there is an easy fix.

Line 1567 of src/Docker/Client/Types.hs, function parseIntegerText, just add MonadFail m to signature:

```
parseIntegerText :: (MonadFail m, Monad m) => Text -> m Integer
parseIntegerText t = case readMaybe $ T.unpack t of
    Nothing ->
        fail "Could not parse Integer"
    Just i ->
        return i

```

thanks for the great work,
Stephen.

**Comment by jprider63** [comment]
Thanks @esjmb! I just made PR #73 that includes this. I'll merge it once CI passes.

**Comment by jprider63** [comment]
@denibertovic can you deploy the new version?

**Comment by denibertovic** [comment]
@jprider63 done! :)
