### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by jprider63** [denibertovic/docker-hs#77]
CI is [broken](https://travis-ci.org/github/denibertovic/docker-hs/builds/669923956).

**Comment by denibertovic** [comment]
Yeah I've looked at that a while ago. I'm actually thinking of not supporting old version of docker like we're currently doing. The API is versioned anyway. And I'd much rather this works with newer version than older ones that probably nobody is using. I'm also thinking about dropping support for older GHC releases. 

I need to dig up the branch I was testing in and merge it.

**Comment by jprider63** [comment]
#87 switched to us github actions. We should improve it to run docker integration tests with `RUN_INTEGRATION_TESTS=1`.

**Comment by denibertovic** [comment]
Thank all. Closing.
