### ISSUE TITLE
Missing Container State: removing

### ISSUE THREAD

**Issue by vst** [denibertovic/docker-hs#90]
By luck (or not), we have seen this:

```txt
DockerClientDecodeError "Error in $[1].State: Unknown Status: String \"removing\""
```

This was thrown while the client requested the state of a container that was being removed.

**Comment by jprider63** [comment]
Sorry for the delay. This should be fixed with #101. Can you let us know if that works for you?

**Comment by vst** [comment]
Looks good to me. I do not know if I can reproduce that state easily, but I will give it a try today.

**Comment by jprider63** [comment]
Ok, let us know. It's simple enough that I'm fine with merging. Thanks for the report!

**Comment by vst** [comment]
> Ok, let us know. It's simple enough that I'm fine with merging. Thanks for the report!

Agreed. Thanks a lot for attending it.
